name: Yaprak Deployment
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Ansible Playbook
        uses: dawidd6/action-ansible-playbook@v4
        with:
          playbook: playbook.yaml
          directory: ./
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          inventory: ${{ secrets.ANSIBLE_INVENTORY }}
          vault_password: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
